language: python

# Mention the python version in which travis will run the app
python:
  - "3.6"


# command to install dependencies in the requirements file
install:
  - pip install -r requirements.txt
  - pip install coverage


# command to run tests to run test files
script:
  - pytest

#after_script:
  - coveralls